/**
 * API Routes for Environment Variables Management
 */

import { Router, type Request, type Response } from 'express';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { ENV_VARIABLES, validateEnvValue, type EnvCategory } from './env-config.js';
import { requireAuth, requireAdmin } from './auth/middleware.js';

export function createEnvRouter(): Router {
  const router = Router();
  const ENV_FILE_PATH = join(process.cwd(), '.env');

  // Helper: Read .env file
  function readEnvFile(): Record<string, string> {
    if (!existsSync(ENV_FILE_PATH)) {
      return {};
    }
    const content = readFileSync(ENV_FILE_PATH, 'utf-8');
    const env: Record<string, string> = {};
    
    content.split('\n').forEach(line => {
      line = line.trim();
      if (!line || line.startsWith('#')) return;
      
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        const [, key, value] = match;
        env[key.trim()] = value.trim().replace(/^["']|["']$/g, '');
      }
    });
    
    return env;
  }

  // Helper: Write .env file
  function writeEnvFile(env: Record<string, string>): void {
    const lines: string[] = [
      '# OpenQA Environment Configuration',
      '# Auto-generated by OpenQA Dashboard',
      '# Last updated: ' + new Date().toISOString(),
      '',
    ];

    // Group by category
    const categories: Record<string, string[]> = {};
    ENV_VARIABLES.forEach(v => {
      if (!categories[v.category]) {
        categories[v.category] = [];
      }
      const value = env[v.key] || '';
      if (value || v.required) {
        categories[v.category].push(`${v.key}=${value}`);
      }
    });

    // Write by category
    const categoryNames: Record<string, string> = {
      llm: 'LLM CONFIGURATION',
      security: 'SECURITY',
      target: 'TARGET APPLICATION',
      github: 'GITHUB INTEGRATION',
      web: 'WEB SERVER',
      agent: 'AGENT CONFIGURATION',
      database: 'DATABASE',
      notifications: 'NOTIFICATIONS',
    };

    Object.entries(categories).forEach(([category, vars]) => {
      if (vars.length > 0) {
        lines.push('# ' + '='.repeat(76));
        lines.push(`# ${categoryNames[category as EnvCategory] || category.toUpperCase()}`);
        lines.push('# ' + '='.repeat(76));
        lines.push(...vars);
        lines.push('');
      }
    });

    writeFileSync(ENV_FILE_PATH, lines.join('\n'));
  }

  // GET /api/env - Get all environment variables (admin only)
  router.get('/api/env', requireAuth, requireAdmin, (_req: Request, res: Response) => {
    try {
      const envFile = readEnvFile();
      const processEnv = process.env;
      
      const variables = ENV_VARIABLES.map(v => ({
        key: v.key,
        value: envFile[v.key] || processEnv[v.key] || '',
        type: v.type,
        category: v.category,
        required: v.required,
        description: v.description,
        placeholder: v.placeholder,
        options: v.options,
        sensitive: v.sensitive,
        testable: v.testable,
        restartRequired: v.restartRequired,
        // Mask sensitive values
        displayValue: v.sensitive && (envFile[v.key] || processEnv[v.key]) 
          ? '••••••••' 
          : envFile[v.key] || processEnv[v.key] || '',
      }));

      res.json({
        variables,
        envFileExists: existsSync(ENV_FILE_PATH),
        lastModified: existsSync(ENV_FILE_PATH) 
          ? new Date(readFileSync(ENV_FILE_PATH, 'utf-8').match(/Last updated: (.+)/)?.[1] || 0).toISOString()
          : null,
      });
    } catch (error: unknown) {
      res.status(500).json({ 
        error: 'Failed to read environment variables',
        details: error instanceof Error ? error.message : String(error)
      });
    }
  });

  // GET /api/env/:key - Get specific environment variable
  router.get('/api/env/:key', requireAuth, requireAdmin, (req: Request, res: Response) => {
    try {
      const { key } = req.params;
      const envVar = ENV_VARIABLES.find(v => v.key === key);
      
      if (!envVar) {
        res.status(404).json({ error: 'Environment variable not found' });
        return;
      }

      const envFile = readEnvFile();
      const value = envFile[key] || process.env[key] || '';

      res.json({
        ...envVar,
        value,
        displayValue: envVar.sensitive && value ? '••••••••' : value,
      });
    } catch (error: unknown) {
      res.status(500).json({ 
        error: 'Failed to read environment variable',
        details: error instanceof Error ? error.message : String(error)
      });
    }
  });

  // PUT /api/env/:key - Update specific environment variable
  router.put('/api/env/:key', requireAuth, requireAdmin, (req: Request, res: Response) => {
    try {
      const { key } = req.params;
      const { value } = req.body;

      // Validate
      const validation = validateEnvValue(key, value);
      if (!validation.valid) {
        res.status(400).json({ error: validation.error });
        return;
      }

      // Read current env
      const env = readEnvFile();
      
      // Update value
      if (value === '' || value === null || value === undefined) {
        delete env[key];
      } else {
        env[key] = value;
      }

      // Write back
      writeEnvFile(env);

      // Update process.env (for immediate effect without restart)
      if (value) {
        process.env[key] = value;
      } else {
        delete process.env[key];
      }

      const envVar = ENV_VARIABLES.find(v => v.key === key);

      res.json({ 
        success: true,
        key,
        value: envVar?.sensitive ? '••••••••' : value,
        restartRequired: envVar?.restartRequired || false,
      });
    } catch (error: unknown) {
      res.status(500).json({ 
        error: 'Failed to update environment variable',
        details: error instanceof Error ? error.message : String(error)
      });
    }
  });

  // POST /api/env/bulk - Update multiple environment variables
  router.post('/api/env/bulk', requireAuth, requireAdmin, (req: Request, res: Response) => {
    try {
      const { variables } = req.body as { variables: Record<string, string> };

      if (!variables || typeof variables !== 'object') {
        res.status(400).json({ error: 'Invalid request body' });
        return;
      }

      // Validate all values first
      const errors: Record<string, string> = {};
      Object.entries(variables).forEach(([key, value]) => {
        const validation = validateEnvValue(key, value);
        if (!validation.valid) {
          errors[key] = validation.error || 'Invalid value';
        }
      });

      if (Object.keys(errors).length > 0) {
        res.status(400).json({ error: 'Validation failed', errors });
        return;
      }

      // Read current env
      const env = readEnvFile();

      // Update all values
      Object.entries(variables).forEach(([key, value]) => {
        if (value === '' || value === null || value === undefined) {
          delete env[key];
          delete process.env[key];
        } else {
          env[key] = value;
          process.env[key] = value;
        }
      });

      // Write back
      writeEnvFile(env);

      const restartRequired = Object.keys(variables).some(key => {
        const envVar = ENV_VARIABLES.find(v => v.key === key);
        return envVar?.restartRequired;
      });

      res.json({ 
        success: true,
        updated: Object.keys(variables).length,
        restartRequired,
      });
    } catch (error: unknown) {
      res.status(500).json({ 
        error: 'Failed to update environment variables',
        details: error instanceof Error ? error.message : String(error)
      });
    }
  });

  // POST /api/env/test/:key - Test environment variable (e.g., API key)
  router.post('/api/env/test/:key', requireAuth, requireAdmin, async (req: Request, res: Response) => {
    try {
      const { key } = req.params;
      const { value } = req.body;

      const envVar = ENV_VARIABLES.find(v => v.key === key);
      if (!envVar || !envVar.testable) {
        res.status(400).json({ error: 'This variable cannot be tested' });
        return;
      }

      let testResult: { success: boolean; message: string };

      // Test based on key
      switch (key) {
        case 'OPENAI_API_KEY':
          testResult = await testOpenAIKey(value);
          break;
        case 'ANTHROPIC_API_KEY':
          testResult = await testAnthropicKey(value);
          break;
        case 'OLLAMA_BASE_URL':
          testResult = await testOllamaURL(value);
          break;
        case 'GITHUB_TOKEN':
          testResult = await testGitHubToken(value);
          break;
        case 'SAAS_URL':
          testResult = await testURL(value);
          break;
        case 'SLACK_WEBHOOK_URL':
          testResult = await testSlackWebhook(value);
          break;
        case 'DISCORD_WEBHOOK_URL':
          testResult = await testDiscordWebhook(value);
          break;
        default:
          testResult = { success: false, message: 'Test not implemented for this variable' };
      }

      res.json(testResult);
    } catch (error: unknown) {
      res.status(500).json({ 
        success: false,
        message: error instanceof Error ? error.message : 'Test failed'
      });
    }
  });

  // POST /api/env/generate/:key - Generate value for environment variable
  router.post('/api/env/generate/:key', requireAuth, requireAdmin, (req: Request, res: Response) => {
    try {
      const { key } = req.params;

      let generated: string;

      switch (key) {
        case 'OPENQA_JWT_SECRET':
          // Generate 32-byte random hex string
          generated = Array.from({ length: 64 }, () => 
            Math.floor(Math.random() * 16).toString(16)
          ).join('');
          break;
        default:
          res.status(400).json({ error: 'Generation not supported for this variable' });
          return;
      }

      res.json({ success: true, value: generated });
    } catch (error: unknown) {
      res.status(500).json({ 
        error: 'Failed to generate value',
        details: error instanceof Error ? error.message : String(error)
      });
    }
  });

  return router;
}

// Test functions
async function testOpenAIKey(apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch('https://api.openai.com/v1/models', {
      headers: { 'Authorization': `Bearer ${apiKey}` },
    });
    if (response.ok) {
      return { success: true, message: 'OpenAI API key is valid' };
    }
    return { success: false, message: 'Invalid OpenAI API key' };
  } catch {
    return { success: false, message: 'Failed to connect to OpenAI API' };
  }
}

async function testAnthropicKey(apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307',
        max_tokens: 1,
        messages: [{ role: 'user', content: 'test' }],
      }),
    });
    if (response.status === 200 || response.status === 400) {
      return { success: true, message: 'Anthropic API key is valid' };
    }
    return { success: false, message: 'Invalid Anthropic API key' };
  } catch {
    return { success: false, message: 'Failed to connect to Anthropic API' };
  }
}

async function testOllamaURL(url: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch(`${url}/api/tags`);
    if (response.ok) {
      return { success: true, message: 'Ollama server is accessible' };
    }
    return { success: false, message: 'Ollama server returned an error' };
  } catch {
    return { success: false, message: 'Cannot connect to Ollama server' };
  }
}

async function testGitHubToken(token: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch('https://api.github.com/user', {
      headers: { 'Authorization': `token ${token}` },
    });
    if (response.ok) {
      const data = await response.json() as { login: string };
      return { success: true, message: `GitHub token is valid (user: ${data.login})` };
    }
    return { success: false, message: 'Invalid GitHub token' };
  } catch {
    return { success: false, message: 'Failed to connect to GitHub API' };
  }
}

async function testURL(url: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch(url, { method: 'HEAD' });
    if (response.ok) {
      return { success: true, message: 'URL is accessible' };
    }
    return { success: false, message: `URL returned status ${response.status}` };
  } catch {
    return { success: false, message: 'Cannot connect to URL' };
  }
}

async function testSlackWebhook(url: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: 'OpenQA webhook test' }),
    });
    if (response.ok) {
      return { success: true, message: 'Slack webhook is valid' };
    }
    return { success: false, message: 'Invalid Slack webhook' };
  } catch {
    return { success: false, message: 'Failed to connect to Slack webhook' };
  }
}

async function testDiscordWebhook(url: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: 'OpenQA webhook test' }),
    });
    if (response.ok || response.status === 204) {
      return { success: true, message: 'Discord webhook is valid' };
    }
    return { success: false, message: 'Invalid Discord webhook' };
  } catch {
    return { success: false, message: 'Failed to connect to Discord webhook' };
  }
}
